In [2]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import torch

# Tensor
At its core , pytorch is a library for processing tensors. A tensor is a number , vector , matrix or any n-dimension array . Let's create a tensor with single number.

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

4. is a shorthand for 4.0 . It is used to indicate python ( and PyTorch) that you want to  create  a floating-point number . We can verify this by checking the data types attribute of our tensor

In [5]:
t1.dtype

torch.float32

Let's create more complex tensor

In [6]:
t2 = torch.tensor([1., 2,3,4])
t2

tensor([1., 2., 3., 4.])

In [8]:
t2.dtype

torch.float32

In [9]:
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [10]:
t4 = torch.tensor([
    [[11,12,13],
    [13,14,15]],
    [[15,16,17],
    [17,18,19.]]
])

In [11]:
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [14]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [15]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

# Tensor Operation And Gradient
 we can combine tensor with the usual arithmetic operations.Let's look at an examples:

In [16]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [17]:
# Arithmetic Operation
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected , y is a tensor with the value 3 *4 +5 = 17 . What makes PyTorch unique is that we can automatically compute the derivates of y w.r. to the sensors that have requires_grad set to True. i.e. w and b . This feature of PyTorch is called auto grad(automatic gradients). 

##To compute the derivates, we can invoke the .backward method on our result y.

In [18]:
#compute derivates
y.backward()

In [19]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As Expected dy/dw has the same value as x, i.e 3 and dy/db has the value 1. Note That x.grad is none because x doesnot have requires_grad set to True.


In [20]:
import numpy as np

x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [22]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [23]:
y.dtype, x.dtype

(torch.float64, dtype('float64'))

In [24]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])