In [1]:
import torch.nn as nn
import numpy as np
import torch


In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

## Dataset and Loader

In [4]:
from torch.utils.data import TensorDataset

In [5]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [6]:
from torch.utils.data import DataLoader

In [7]:
#define data loader
batch_size = 5
train_d1 = DataLoader(train_ds, batch_size, shuffle = True)

In [8]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [9]:
for xb, yb in train_d1:
  print(xb)
  print(yb)

tensor([[ 68.,  96.,  71.],
        [ 88., 134.,  59.],
        [ 87., 135.,  57.],
        [ 91.,  87.,  65.],
        [ 74.,  66.,  43.]])
tensor([[104., 118.],
        [118., 132.],
        [118., 134.],
        [ 80., 102.],
        [ 57.,  69.]])
tensor([[ 68.,  97.,  70.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [103.,  43.,  36.],
        [ 87., 134.,  58.]])
tensor([[102., 120.],
        [103., 119.],
        [ 22.,  37.],
        [ 20.,  38.],
        [119., 133.]])
tensor([[ 91.,  88.,  64.],
        [ 92.,  87.,  64.],
        [ 73.,  66.,  44.],
        [101.,  44.,  37.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [ 82., 100.],
        [ 57.,  69.],
        [ 21.,  38.],
        [ 56.,  70.]])


In each iteration, the data loader returns one batch of data with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

## nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [10]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4036, -0.1865,  0.0842],
        [-0.0035,  0.3104, -0.0389]], requires_grad=True)
Parameter containing:
tensor([-0.3916, -0.4856], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [11]:
#parameter
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4036, -0.1865,  0.0842],
         [-0.0035,  0.3104, -0.0389]], requires_grad=True),
 Parameter containing:
 tensor([-0.3916, -0.4856], requires_grad=True)]

In [12]:
# Generate prediction
preds = model(inputs)
preds

tensor([[20.1928, 18.3860],
        [25.3079, 24.0251],
        [14.6092, 38.5525],
        [35.8682, 11.0683],
        [15.4418, 26.3514],
        [20.7829, 18.0720],
        [25.5786, 23.6757],
        [15.0970, 38.5101],
        [35.2781, 11.3822],
        [15.1224, 26.3160],
        [20.4635, 18.0366],
        [25.8980, 23.7111],
        [14.3386, 38.9019],
        [36.1876, 11.1038],
        [14.8517, 26.6653]], grad_fn=<AddmmBackward0>)

In [13]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [14]:
# Import nn.functional
import torch.nn.functional as F

The nn.functional package contains many usefull loss function and several other utilies

In [15]:
# Define loss function
loss_fn = F.mse_loss

In [16]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4981.1626, grad_fn=<MseLossBackward0>)


## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term _stochastic_ indicates that samples are selected in random batches instead of as a single group.


In [17]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that `model.parameters()` is passed as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

## Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [29]:
# utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_d1):
  # reapeat for the given number of epochs
  for epoch in range(num_epochs):
    # train with batches of data
    for xb, yb in train_d1:
      # 1. Generate Prediction
      pred = model(xb)

      # 2. Calculate loss 
      loss = loss_fn(pred, yb)

      # 3. Compute Gradients
      loss.backward()

      # 4. Update parameters using gradients
      opt.step()

      # 5. REset the gradient to zero
      opt.zero_grad()
    # print the progess
    
    if (epoch+1) % 10 == 0:
      print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')



In [30]:
fit(100,model, loss_fn,opt,train_d1)

Epoch [10/100], Loss: 93.1673
Epoch [20/100], Loss: 48.4300
Epoch [30/100], Loss: 49.7156
Epoch [40/100], Loss: 28.5593
Epoch [50/100], Loss: 34.2131
Epoch [60/100], Loss: 34.8422
Epoch [70/100], Loss: 30.6446
Epoch [80/100], Loss: 22.7767
Epoch [90/100], Loss: 18.1404
Epoch [100/100], Loss: 22.9838


In [31]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.6556,  71.0433],
        [ 80.9742,  97.7509],
        [119.6313, 138.7888],
        [ 25.0126,  41.1131],
        [ 97.4818, 111.5455],
        [ 56.4795,  69.9460],
        [ 80.5838,  97.2792],
        [119.8210, 139.0986],
        [ 26.1887,  42.2104],
        [ 98.2676, 112.1710],
        [ 57.2653,  70.5715],
        [ 79.7980,  96.6536],
        [120.0216, 139.2605],
        [ 24.2268,  40.4876],
        [ 98.6579, 112.6427]], grad_fn=<AddmmBackward0>)

In [32]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])